name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  workflow:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Verify Python Version
        run: python -c "import sys; print(sys.version)"

      - name: Format
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."

      - name: Run Tests
        uses: pavelzw/pytest-action@v2
